name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: lint:js
      run: yarn lint:js

  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: ember test
      run: yarn test:ember

  floating-dependencies:
    name: Floating Deps
    runs-on: ubuntu-latest

    needs: [test, lint]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install
    - name: ember test
      run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest

    needs: [test, lint]

    strategy:
      matrix:
        ember-try-scenario:
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic
          - embroider-tests

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
